# Generated by Django 5.0.6 on 2024-09-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token_send',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
