# Generated by Django 5.0.6 on 2024-05-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='PostCode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
