# Generated by Django 5.0.6 on 2024-09-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_otp_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
