# Generated by Django 5.0.6 on 2024-05-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customer_first_name_remove_customer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='PhoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='PostCode',
            new_name='post_Code',
        ),
    ]
