# Generated by Django 5.0.6 on 2024-10-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(default=12345678, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
