# Generated by Django 5.0.6 on 2024-10-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_address_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='post_Code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
