# Generated by Django 5.0.6 on 2024-06-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default=5, max_length=30),
            preserve_default=False,
        ),
    ]
