# Generated by Django 5.0.6 on 2024-09-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number_of_ratings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='star_rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_rating',
        ),
    ]
