# Generated by Django 5.0.6 on 2024-12-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='peyment',
            new_name='payment',
        ),
    ]
