# Generated by Django 5.0.6 on 2024-11-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
