# Generated by Django 5.0.6 on 2024-06-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='peyment',
            field=models.BooleanField(default=False),
        ),
    ]
