# Generated by Django 5.0.6 on 2024-06-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_peyment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='peyment',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='peyment',
            field=models.BooleanField(default=False),
        ),
    ]
