# Generated by Django 5.0.6 on 2024-06-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='star_rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
