# Generated by Django 5.0.6 on 2024-11-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_basketitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
