# Generated by Django 5.0.6 on 2024-12-11 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_peyment_basketitem_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(default=0.0, help_text='Discount percentage for the product (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_percentage',
            field=models.FloatField(default=0.0, help_text='Discount percentage for the variant (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
