# Generated by Django 5.0.6 on 2024-06-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_product_peyment_basketitem_peyment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
    ]
