# Generated by Django 5.0.6 on 2024-06-25 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_number_of_ratings_product_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
