# Generated by Django 5.0.6 on 2024-06-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star_rating',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
