# Generated by Django 5.0.6 on 2024-07-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_color_remove_product_color_product_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='colors',
        ),
    ]
