# Generated by Django 5.0.6 on 2024-07-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default=11111, max_length=7),
            preserve_default=False,
        ),
    ]
