# Generated by Django 5.0.6 on 2024-06-05 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
