# Generated by Django 5.0.6 on 2024-06-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
